### ISSUE TITLE
Platform error climate.fht_heating - Requirements for fht_heating not found: ['requests==2.25.1

### ISSUE THREAD

**Issue by yasapl** [Rsclub22/home-assistant-fht#2]
As per subject I’m receiving an error when checking the configuration. Files copied to cystom component / fht_heating dir.

Platform error climate.fht_heating - Requirements for fht_heating not found: ['requests==2.25.1

any idea what does that mean?

**Comment by Rsclub22** [comment]
it means, that there is an == in the manifest.json, you can retry now with v0.3

**Comment by Rsclub22** [comment]
Use this: https://github.com/Rsclub22/home-assistant-fht/releases/download/v.0.3/fht_heating.zip and then tell me if it worked

**Comment by Rsclub22** [comment]
As per what idea what that means, it ment that the programm required a specific version of the modules, which are no longer compatible with homeassistant.

**Comment by yasapl** [comment]
thanks mate, it worked!
